### ISSUE TITLE
Redirect issue

### ISSUE THREAD

**Issue by AnimishY** [mezbaulanam/LinkSimplify#6]
![image](https://github.com/user-attachments/assets/f7cabdb1-ab51-4dd3-8abd-8ac1b6a8e4cd)
Hey, So I created this shortened link and when I click the link, it opens in a new tab: first the short-link: https://linksimplify-57f95a96384c.herokuapp.com/wCP3q3 and then it should convert to animishy.co for this example but instead it converts to https://linksimplify-57f95a96384c.herokuapp.com/animishy.co (it's assuming that the long URL is a sub-page of the main project instead being an individual website.

**Comment by mezbaulanam** [comment]
@AnimishY You need to put https:// or http:// in Long URL :) https://animishy.co , http://animishy.co , That should work!

**Comment by mezbaulanam** [comment]
I will soon make validators for the Long URL Field I guess to minimize the misunderstanding
